### ISSUE TITLE
Problem with react-native-simple-markdown handling some youtube or video content

### ISSUE THREAD

**Issue by staltz** [staltz/manyverse#10]
From @alanz in issue #9 

> **Steps to reproduce the bug:**
>
> Start up the app. [having previously established friendship, so major sync happens]
>
> **Expected behavior:**
>
> Syncs, stays up
>
> **Actual behavior:**
>
> Syncs for a while, then app dies
>
> **Technical details**
>
> - MMMMM app version: 0.0.8-alpha
> - Device/phone model: OnePlus 5
> - Android OS version: 7.1.1
>
>And I guess it is content related. After syncing a bit more, it crashes with
>
> ```
> 1-29 14:50:08.726 17051 17093 V nodejs  :   error: 'Error: challenge not accepted\n    at abort (/data/data/com.mmmmm/rnnodeapp/index.js:68584:45)\n    at Object.cb (/data/data/com.mmmmm/rnnodeapp/index.js:68590:24)\n    at drain (/data/data/com.mmmmm/rnnodeapp/index.js:48904:23)\n    at /data/data/com.mmmmm/rnnodeapp/index.js:48921:18\n    at /data/data/com.mmmmm/rnnodeapp/index.js:48882:7\n    at /data/data/com.mmmmm/rnnodeapp/index.js:67055:9\n    at drain (/data/data/com.mmmmm/rnnodeapp/index.js:68878:18)\n    at Socket.<anonymous> (/data/data/com.mmmmm/rnnodeapp/index.js:68899:5)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)',
> 11-29 14:50:08.726 17051 17093 V nodejs  :   state: undefined }
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS: TypeError: undefined is not an object (evaluating 't.target.match')
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS: 
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS: This error is located at:
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in r
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTScrollView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in ScrollView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in AndroidViewPager
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in n
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in p
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in n
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in RCTView
> 11-29 14:50:09.321 17051 17080 E ReactNativeJS:     in t
> 11-29 14:50:09.332 17051 17080 E ReactNativeJS: TypeError: undefined is not an object (evaluating 't.target.match')
>```
>
> And this is *alpha* code. But nice to see it shaping up.

**Comment by staltz** [comment]
Might be related to `react-native-simple-markdown/rules.js` => `image`
