### ISSUE TITLE
npm run build-backend-android failed when running neon-load-or-build

### ISSUE THREAD

**Issue by SeanXu1984** [staltz/manyverse#78]
I was trying to build the project but I got the following error for Android when building backend (npm run build-backend-android).

```
npm info lifecycle ssb-keys-neon@8.0.0-8~install: ssb-keys-neon@8.0.0-8

> ssb-keys-neon@8.0.0-8 install /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
> neon-load-or-build

(node:3874) ExperimentalWarning: The fs.promises API is experimental
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: unsafe-perm in lifecycle true
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: PATH: /Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/node_modules/.bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/.bin:/Users/seanxu/.sdkman/candidates/gradle/current/bin:/Users/seanxu/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/seanxu/Library/Android/sdk/emulator:/Users/seanxu/Library/Android/sdk/tools:/Users/seanxu/Library/Android/sdk/tools/bin:/Users/seanxu/Library/Android/sdk/platform-tools:/Users/seanxu/Downloads/cmdline-tools/bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: CWD: /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
npm info lifecycle ssb-keys-neon@8.0.0-8~install: Failed to exec install script
npm verb stack Error: ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid ssb-keys-neon@8.0.0-8
npm verb cwd /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project
npm verb Darwin 18.2.0
npm verb argv "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/node" "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-keys-neon@8.0.0-8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 151391ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-11T12_09_22_972Z-debug.log
seans-mac:nodejs-project seanxu$ cd /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
seans-mac:ssb-keys-neon seanxu$ "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/node" "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm info it worked if it ends with ok
npm verb cli [ '/Users/seanxu/.nvm/versions/node/v10.13.0/bin/node',
npm verb cli   '/Users/seanxu/.nvm/versions/node/v10.13.0/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'rebuild',
npm verb cli   '--build-from-source' ]
npm info using npm@6.4.1
npm info using node@v10.13.0
npm info readInstalled object
npm verb rebuild path, id [ '/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon',
npm verb rebuild   'ssb-keys-neon@8.0.0-8' ]
npm verb exit [ 0, true ]
npm timing npm Completed in 728ms
npm info ok 
```

The installation of ssb-keys-neon failed when running neon-load-or-build.

If I install ssb-keys-neon separately using npm install ssb-keys-neon I will not get such error.

node version v10.13.0
npm version 6.4.1

**Comment by staltz** [comment]
Hi! Just to check, have you read `CONTRIBUTING.md` carefully?

**Comment by SeanXu1984** [comment]
I believe I have followed the instructions from CONTRIBUTING.md

**Comment by staltz** [comment]
Okay. So you have Rust and Cargo installed. There is an issue with neon-load-or-build where it reports an error, but everything is still executing correctly afterwards. Did you cancel the build manually when you saw the error, have you tried to let it continue running?

**Comment by SeanXu1984** [comment]
The process would fail right after the neon-load-or-build error.

```
npm info build /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
npm info lifecycle ssb-keys-neon@8.0.0-8~preinstall: ssb-keys-neon@8.0.0-8
npm info linkStuff ssb-keys-neon@8.0.0-8
npm info lifecycle ssb-keys-neon@8.0.0-8~install: ssb-keys-neon@8.0.0-8
(node:3198) ExperimentalWarning: The fs.promises API is experimental
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: unsafe-perm in lifecycle true
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: PATH: /Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/node_modules/.bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/.bin:/Users/seanxu/Desktop/manyverse/android/../nodejs-assets/nodejs-project/node_modules/.bin:/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin:/Users/seanxu/.sdkman/candidates/gradle/current/bin:/Users/seanxu/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/seanxu/Library/Android/sdk/emulator:/Users/seanxu/Library/Android/sdk/tools:/Users/seanxu/Library/Android/sdk/tools/bin:/Users/seanxu/Library/Android/sdk/platform-tools:/Users/seanxu/Downloads/cmdline-tools/bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: CWD: /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
npm info lifecycle ssb-keys-neon@8.0.0-8~install: Failed to exec install script
npm verb stack Error: ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid ssb-keys-neon@8.0.0-8
npm verb cwd /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project
npm verb Darwin 18.2.0
npm verb argv "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/node" "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-keys-neon@8.0.0-8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 225800ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-12T10_22_14_278Z-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodejs-mobile-react-native:BuildNpmModulesarmeabi-v7a'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15m 10s
Unhandled script error 1 at ./tools/backend/build-native-modules.sh:32

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manyverse@0.2101.5-beta build-backend-android: `./tools/build-backend.js --android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manyverse@0.2101.5-beta build-backend-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-12T10_22_20_758Z-debug.log
```

**Comment by staltz** [comment]
I think `spawn cargo ENOENT` means that it cannot find Cargo (a Rust CLI). Can you make sure Cargo is correctly installed?

**Comment by SeanXu1984** [comment]
Thanks a lot. Now Cargo is installed but I got some error complaining some dylib is missing.

```
     Running `rustc --crate-name ssb_neon_keys --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=54ef060f9a763f60 --out-dir /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps --target arm-linux-androideabi -C linker=/Users/seanxu/Desktop/manyverse/android/build/standalone-toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-clang++ -L dependency=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps -L dependency=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/release/deps --extern arrayvec=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libarrayvec-8899d7ba67175fce.rlib --extern base64=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libbase64-5da39487e537db3a.rlib --extern neon=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libneon-f3e27280ce89ed8d.rlib --extern private_box=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libprivate_box-766490cb56a79315.rlib --extern ssb_crypto=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libssb_crypto-2d426d0ea46023cc.rlib --extern ssb_keyfile=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/deps/libssb_keyfile-7b5a07ac804d9351.rlib -L /Users/seanxu/Desktop/manyverse/node_modules/nodejs-mobile-react-native/android/libnode/bin/armeabi-v7a -l node -L native=/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/build/neon-sys-0bc4170af3b95ab4/out`
    Finished release [optimized] target(s) in 1m 14s
neon ERR! ENOENT: no such file or directory, copyfile '/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/libssb_neon_keys.dylib' -> '/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/index.node'

Error: ENOENT: no such file or directory, copyfile '/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/libssb_neon_keys.dylib' -> '/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/index.node'
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: unsafe-perm in lifecycle true
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: PATH: /Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/node_modules/.bin:/Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/.bin:/Users/seanxu/Desktop/manyverse/android/../nodejs-assets/nodejs-project/node_modules/.bin:/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin:/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin:/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin:/Users/seanxu/.sdkman/candidates/gradle/current/bin:/Users/seanxu/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/seanxu/Library/Android/sdk/emulator:/Users/seanxu/Library/Android/sdk/tools:/Users/seanxu/Library/Android/sdk/tools/bin:/Users/seanxu/Library/Android/sdk/platform-tools:/Users/seanxu/Downloads/cmdline-tools/bin:/Users/seanxu/Desktop/manyverse/node_modules/.bin:/Users/seanxu/.cargo/bin
npm verb lifecycle ssb-keys-neon@8.0.0-8~install: CWD: /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon
npm info lifecycle ssb-keys-neon@8.0.0-8~install: Failed to exec install script
npm verb stack Error: ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/Users/seanxu/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid ssb-keys-neon@8.0.0-8
npm verb cwd /Users/seanxu/Desktop/manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project
npm verb Darwin 18.2.0
npm verb argv "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/node" "/Users/seanxu/.nvm/versions/node/v10.13.0/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-keys-neon@8.0.0-8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 249082ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-13T01_39_53_966Z-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodejs-mobile-react-native:BuildNpmModulesarmeabi-v7a'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 56s
Unhandled script error 1 at ./tools/backend/build-native-modules.sh:32

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manyverse@0.2101.5-beta build-backend-android: `./tools/build-backend.js --android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manyverse@0.2101.5-beta build-backend-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-13T01_40_02_394Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manyverse@0.2101.5-beta build-android-assets: `npm run lib && npm run propagate-replacements && npm run build-backend-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manyverse@0.2101.5-beta build-android-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-13T01_40_02_421Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manyverse@0.2101.5-beta android-dev: `npm run build-android-assets && react-native run-android --variant=indieDebug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manyverse@0.2101.5-beta android-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanxu/.npm/_logs/2021-02-13T01_40_02_461Z-debug.log
seans-mac:manyverse seanxu$ npm run full-clean

> manyverse@0.2101.5-beta full-clean /Users/seanxu/Desktop/manyverse
> npm run clean-android && npm run clean-bundler && rm -rf node_modules && rm -rf lib


> manyverse@0.2101.5-beta clean-android /Users/seanxu/Desktop/manyverse
> adb uninstall se.manyver && cd android && ./gradlew clean

* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
```
Not be able to find manyverse/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/ssb-keys-neon/native/target/arm-linux-androideabi/release/libssb_neon_keys.dylib

**Comment by staltz** [comment]
@SeanXu1984 Sorry it took so long to get back to this. I think we have a problem with supporting building the Android app from macOS desktops. But I recently added an option to disable Rust, that may help when building Android from macOS. Can you try `./tools/build-backend.js --android --no-rust`?

**Comment by SeanXu1984** [comment]
Thanks. I had to change sed --in-place to sed -i as --in-place was not recognized on my MacOS.
I will keep you updated.

**Comment by Powersource** [comment]
hoping this is resolved, especially as the rust components are removed now. let us know if you still have problems!
